use std::env;
use prost_build;
use cbindgen;
use cbindgen::Language;

fn main() {
    generate_protobuf_files();
    generate_c_header_bindings();
}

fn generate_protobuf_files() {
    println!("cargo:rerun-if-changed=protobuf_schemata/roll_request.proto");
    println!("cargo:rerun-if-changed=protobuf_schemata/roll_response.proto");

    let mut config = prost_build::Config::default();

    config.out_dir("src/roll_generated");

    config.compile_protos(
        &[
            "protobuf_schemata/roll_request.proto",
            "protobuf_schemata/roll_response.proto",
        ],
        &["protobuf_schemata/"],
    ).unwrap();
}

fn generate_c_header_bindings() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_language(Language::C)
        .with_autogen_warning(
            "/* \n\
            Warning, this file is autogenerated by cbindgen. \n\
            Don't modify this manually. \n\
            */",
        )
        .generate()
        .expect("Unable to generate cbindgen bindings")
        .write_to_file("./generated_c_headers/lib_dice_roller_bindings.h");
}
