use cbindgen;
use cbindgen::Language;
use std::env;

fn main() {
    generate_c_header_bindings();
}

fn generate_c_header_bindings() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_language(Language::C)
        .with_autogen_warning(
            "/* \n\
            Warning, this file is autogenerated by cbindgen. \n\
            Don't modify this manually. \n\
            */",
        )
        .generate()
        .expect("Unable to generate cbindgen bindings")
        .write_to_file("./generated_c_headers/lib_dice_roller_bindings.h");
}
