name: Android Pipeline

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

env:
  CARGO_TERM_COLOR: always

jobs:
  test-and-build-android:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust Android Dependencies
      run: make install-android-dependencies
      working-directory: common/lib-dice-roller
    - name: Symlink Android NDK
      run: ln -s $HOME/Library/Android/sdk/ndk-bundle android-ndk
      working-directory: common/lib-dice-roller
    - name: Setup Rust Cargo Config for Android NDK
      run: mkdir -p .cargo && cp cargo-config.toml .cargo/config.toml
      working-directory: common/lib-dice-roller
    - name: Build Rust Android Library
      run: make build-android
      working-directory: common/lib-dice-roller
