name: iOS Pipeline

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

env:
  CARGO_TERM_COLOR: always

jobs:
  test-and-build-ios:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust iOS Dependencies
      run: make install-dependencies
      working-directory: common/dice-roller-ffi
    - name: Build Rust iOS Library
      run: make build
      working-directory: common/dice-roller-ffi

    - name: Force xcode 11.7
      run: sudo xcode-select -switch /Applications/Xcode_11.7.app

    - name: Run iOS Platform Wrapper Tests
      run: make test
      working-directory: platform-adapters/ios
    - name: Build iOS Platform Wrapper
      run: make build
      working-directory: platform-adapters/ios

    - name: Run iOS Application Tests
      run: make test
      working-directory: applications/ios
    - name: Build iOS Application
      run: make build
      working-directory: applications/ios
