name: Rust

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: common/lib-dice-roller
    steps:
    - uses: actions/checkout@v2
    - name: Install Brew Dependencies
      run: brew bundle
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
