name: Rust Pipeline

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

env:
  CARGO_TERM_COLOR: always

jobs:
  test-rust-library:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Build Rust Library
      run: make build
      working-directory: common/dice-roller
    - name: Run Rust Library Tests
      run: make test
      working-directory: common/dice-roller
