name: Wasm Pipeline

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

env:
  CARGO_TERM_COLOR: always

jobs:
  test-rust-library:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust Wasm Dependencies
      run: make install-wasm-dependencies
      working-directory: common/lib-dice-roller
    - name: Build Rust Wasm Library
      run: make build-wasm
      working-directory: common/lib-dice-roller
    - name: Run Rust Wasm Library Tests
      run: make test-wasm
      working-directory: common/lib-dice-roller
